dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
description: A new Flutter project.
dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: ^3.5.3
flutter:
  uses-material-design: true
name: heartguard
publish_to: none
version: 1.0.0+1
