dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  sqflite: ^2.4.1

description: A new Flutter project.

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ^3.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/img/ecg home page.png
    - assets/img/avatar.png
    - assets/img/ecg watch.png
    - assets/img/background.png
    - assets/img/ecg img.png
    - assets/img/images.png


name: heartguard
publish_to: none
version: 1.0.0+1
