// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Nl9us2UBIF_9AOjYjrojJ2Fl5v7zzBE',
    appId: '1:872244640879:web:0ede0a68d4c6a29c2a619a',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    authDomain: 'heart-guard-1c49e.firebaseapp.com',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAljUNCr6Qh6FikDif2oDZ6tU38wENopC0',
    appId: '1:872244640879:android:80862f715a5e573a2a619a',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpxM21dR9_c4hZViLaw5uZTg-MoSxwhHo',
    appId: '1:872244640879:ios:3a10512fe7280bf82a619a',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.firebasestorage.app',
    iosBundleId: 'com.example.heartguardapp05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpxM21dR9_c4hZViLaw5uZTg-MoSxwhHo',
    appId: '1:872244640879:ios:3a10512fe7280bf82a619a',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.firebasestorage.app',
    iosBundleId: 'com.example.heartguardapp05',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Nl9us2UBIF_9AOjYjrojJ2Fl5v7zzBE',
    appId: '1:872244640879:web:cab6a84003effd672a619a',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    authDomain: 'heart-guard-1c49e.firebaseapp.com',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.firebasestorage.app',
  );

}