// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for $defaultTargetPlatform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Nl9us2UBIF_9AOjYjrojJ2Fl5v7zzBE',
    appId: '1:872244640879:web:d4e8e8d4e8e8d4e8e8d4e8',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    authDomain: 'heart-guard-1c49e.firebaseapp.com',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Nl9us2UBIF_9AOjYjrojJ2Fl5v7zzBE',
    appId: '1:872244640879:android:d4e8e8d4e8e8d4e8e8d4e8',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Nl9us2UBIF_9AOjYjrojJ2Fl5v7zzBE',
    appId: '1:872244640879:ios:d4e8e8d4e8e8d4e8e8d4e8',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.appspot.com',
    iosBundleId: 'com.example.heartguardapp05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Nl9us2UBIF_9AOjYjrojJ2Fl5v7zzBE',
    appId: '1:872244640879:macos:d4e8e8d4e8e8d4e8e8d4e8',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.appspot.com',
    iosBundleId: 'com.example.heartguardapp05',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Nl9us2UBIF_9AOjYjrojJ2Fl5v7zzBE',
    appId: '1:872244640879:windows:d4e8e8d4e8e8d4e8e8d4e8',
    messagingSenderId: '872244640879',
    projectId: 'heart-guard-1c49e',
    databaseURL: 'https://heart-guard-1c49e-default-rtdb.firebaseio.com',
    storageBucket: 'heart-guard-1c49e.appspot.com',
  );
}
